name: DotNet Core Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo $GITHUB_WORKSPACE
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project
        
    - name: Setup Dotnet 2.2.300
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.300'
    
    - name: 'Run dotnet build'
      shell: bash
      run: |
        # If your web app project is not located in your repository's root
        # Please consider using pushd to change your path
        ls $GITHUB_WORKSPACE
        pushd $GITHUB_WORKSPACE/Source
        dotnet build ./SmartHotel360.Website.sln --configuration Release --output ./output
        popd

    - name: workspace after build
      run: echo $GITHUB_WORKSPACE      
    
