name: DotNet Core Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo $GITHUB_WORKSPACE
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project
        
    - name: Setup Dotnet 2.2.300
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.300'
    
    - name: 'Run dotnet build'
      shell: bash
      run: |
        # If your web app project is not located in your repository's root
        # Please consider using pushd to change your path
        echo ${{ github.workspace }}
        ls ${{ github.workspace }}        
        pushd $GITHUB_WORKSPACE/Source
        dotnet build ./SmartHotel360.Website.sln --configuration Release --output ./output
        mkdir package
        dotnet pack --no-build -c Release --output "${{ github.workspace }}/package"
        popd
        ls ${{ github.workspace }}

  #  - name: Upload artifact
  #    uses: actions/upload-artifact@v1.0.0
  #    with:
    # Artifact name
  #      name: nuget
    # Directory containing files to upload
  #      path: $GITHUB_WORKSPACE/package
    
    - name: workspace after build
      run: |
        echo $GITHUB_WORKSPACE 
        ls $GITHUB_WORKSPACE/Source
        ls $GITHUB_WORKSPACE     
    
